# What's the point of using numpy.array if we already have list[] DS? 🤔
let's create a List L and a Numpy Array A and see the difference!

In [1]:
import numpy as np

In [49]:
L = [1,2,3]
A = np.array([1,2,3])
print(f'L={L}, A={A}')

L=[1, 2, 3], A=[1 2 3]


So as you saw the output of both in the initial step is the same!
But let's do some Mathematic operations on the them and see whether they are different or not!

In [11]:
L.append(4)
print(L)
A.append(4)

[1, 2, 3, 4]


AttributeError: 'numpy.ndarray' object has no attribute 'append'

So as you saw, `append` method worked on our List L, however, we got an error while doing the same on our Numpy Array A. Therefore, we understood that the `append` method is not working on the Numpy Array.
There is another way of joining an element to a list, right? we can use the `+` operator! 🤓 But what about Numpy Array?

In [16]:
L = L + [5]
L

[1, 2, 3, 4, 5]

In [21]:
A = A + [4,5]
A

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

It didn't word on the Numpy Array, right? 
So it seems like we don't have the concept of adding to a Numpy Array.
So by now ya might think, if it does not have such simple operations then why should we use it? 🤔

**Here is why: 👇**
Let's try vector addition on the two arrays!
In the case of a Python List (L), we know that if we use the `+` operator, it will just concatenate all the elements to at the end! But it's not really what we want! 
So the way we can achieve this would be using another List (L2) and then create a `for loop` to add the elements of L and L2 to L, right?

However, in the case of a Numpy Array (A), we can simply get to our target by using the `+` operator!

In [39]:
L2 = []
for i in L:
    L2.append(i+i)

A2 = A + A

print(L2)
A2



[2, 4, 6]


array([2, 4, 6])

So that's the first Lesson!
## Lesson 1: 🤓
the **`+`** operator in **Python List** will do a concatanation, however this operation will do element-wise addition in the case of a **Numpy Array**.

The same goes for multipication, pow either! Meaning of you multipy a number to a list, it just repeat the numbers in the list 2 times, however in the case of a Numpy Array, it will multiply in element-wise fashion!

Try it yourself!

In [45]:
A = A**2
A

array([1, 4, 9])

In [47]:
A = np.sqrt(A)
A

array([1.        , 1.41421356, 1.73205081])

In [48]:
A= np.log(A)
A

array([0.        , 0.34657359, 0.54930614])

In [50]:
A = np.exp(A)
A

array([ 2.71828183,  7.3890561 , 20.08553692])

## Note:🔥
One thing to node as ya probabely figure is that Numpy most of the times do operations in **element-wise** fashion.
If ya wanna do the same operations for Python List, then ya need to use the **`for loop`**! 

So in summary when we wanna represent a Vector, Numpy Array is probabely a better choice! Since it has the operations we want! Also for loops are pretty slow in Python!

## Numpy Array Dot Product vs Python List Dot Product 😜
Imagine we have two different arrays that we wanna calculate the `dot product` between those! This is the one formula we use to calculate the `dot product`! 👇

![dot product](./img/dot1.png)

Suppose that we have two arrays, then we aim to calculate the `dot product` using NumPy builtin functions VS. treating it as a `for loop` in python!

In [22]:
#Approach 1; using for loop
def dot_product(a,b):
    result = 0
    for e, f in zip(a,b):
        result += e*f
    print(result)

a = np.array([1,3])
b = np.array([2,5])

print(dot_product(a,b))



17
None


In [26]:
#Approach 2; Using NumpyStack
print(np.sum(a*b)) # or (a*b).sum() because sum itself is an instance of numpy!
#Alternatively we can use the dot builtin function for this!
print(np.dot(a,b)) #like the sum, dot is also and instance method of numpy Array
print(a.dot(b)) #So ya can alternatively use it this way!

17
17
17


## Why NumPy Array is faster than Python List? 🤔
- Array stores in contiguous form in memory, while list not!
- NumPy Array breaks the data into smaller chunks then calculate in parallel!